#!/bin/bash

while true; do
    current=`cat ~/.amp.current`
    dir=`dirname "$current"`
    picture="$dir/sleeve.jpg"

    temp=`cat ~/jukebox/tex/tempdata.data`
    track=`cat ~/jukebox/tex/tdata.txt`

    if [ "$prev" != "$current" ]; then
	sleep 2
	if [ ! -e "$dir/.nodisplay" ]; then
	    # Create the image for Quimbies
	    ~/src/smalldisplay/makedisplay "$picture" "$track"
	    xscreensaver-getimage -display :1\
	        -file /tmp/smalldisplay.png -root
	    # Create the image for Stories
	    ~/src/smalldisplay/makedisplay "$picture" "$track"\
                25 2 "$temp"
	fi
	prev="$current"
    fi
    sleep 1
done

