#!/bin/bash

# This script loops continually on a machine and checks whether a new
# song has started playing.  This is just an example of how I use the
# "makedisplay" script, and is not useful as anything but an example.

while true; do
    current=`cat ~/.amp.current`
    dir=`dirname "$current"`
    picture="$dir/sleeve.jpg"

    temp=`cat ~/jukebox/tex/tempdata.data`
    track=`cat ~/jukebox/tex/tdata.txt`

    if [ "$prev" != "$current" -a "$track" != "$prevtrack" ]; then
	if [ ! -e "$dir/.nodisplay" ]; then
	    # Create and display the image for Quimbies
	    ~/src/smalldisplay/makedisplay "$picture" "$track"
	    xscreensaver-getimage -display :1\
	        -file /tmp/smalldisplay.png -root
	    # Create and copy the image for Stories
	    ~/src/smalldisplay/makedisplay "$picture" "$track"\
                25 2 "\parbox{4cm}{\begin{flushright}$temp\end{flushright}}"
	    cp /tmp/smalldisplay.tiff ~/jukebox/tex/smalldisplay25.tiff
	fi
	prev="$current"
	prevtrack="$track"
    fi
    sleep 1
done

