#!/bin/bash

screenWidth=800
screenHeight=480

image="$1"
bottomText="$2"
fontSize="$3"
blurTimes="$4"
topText="$5"

if [ "$bottomText" = "" ]; then
    echo "Usage: $0 <image> <font-size> <blur-times> <bottomText> <topText>"
    exit
fi

if [ "$fontSize" = "" ]; then
    fontSize=40
fi

if [ "$blurTimes" = "" ]; then
    blurTimes=3
fi    

cd /tmp
baseDir=`dirname $0`

cp "$baseDir/text.tex" .
cp "$baseDir/pfur8a.pfb" .

# First create the text(s)
for type in bottom top; do
    var="${type}Text"
    text=${!var}
    if [ "$text" != "" ]; then
	echo "\fontfamily{pfu}\fontsize{$fontSize}{${fontSize}pt}\selectfont" >\
            textdata.tex
	echo "$text" >> textdata.tex

	latex text.tex
	dvips -f <text.dvi |\
            sed 's/%%EndSetup/-90 rotate -880 -580 translate/' >text.ps
	gs -q -sDEVICE=ppm -r200x200 -g385x2200 -sOutputFile=- -dNOPAUSE\
            text.ps < /dev/null | pnmcut 0 0 385 2200 | pnmflip -r90 |\
            pnminvert > "$type.pnm"

	xsize=`pnmfile $type.pnm | awk '{ print $4; }'`
	cp $type.pnm alpha.pnm
	# Blur the generated text to create the alpha channel.
	for i in `seq 1 $blurTimes`; do
	    pnmsmooth -size 3 3 alpha.pnm | ppmtopgm |\
                pgmtopbm -threshold -value 0.1 | pbmtopgm 3 3 > alpha2.pnm
	    mv alpha2.pnm alpha.pnm
	done
	cat alpha.pnm > alpha$type.pgm
     fi
done

# We accept only png and jpeg files
if `echo "$image" | grep 'png$' >/dev/null`; then
    command=pngtopnm
else
    command=djpeg
fi

$command "$image" | pnmscale -xsize=$screenWidth > image.pnm
ysize=`pnmfile image.pnm | awk '{ print $6; }'`
top=`expr $ysize - $screenHeight`
top=`expr $top / 2`
pnmcut 0 $top $screenWidth $screenHeight image.pnm > imagecut.pnm
ppmmake black $screenWidth $screenHeight > background.pnm
pnmpaste -replace imagecut.pnm 0 0 background.pnm > sd1.pnm

# Finally combine the texts with the alpha channels and the background
# image.
if [ "$topText" != "" ]; then
    theight=`pnmcrop alphabottom.pgm | pnmfile | awk '{ print $6; }'`
    yoff=`expr $screenHeight - $theight - 10`
    twidth=`pnmcrop alphatop.pgm | pnmfile | awk '{ print $4; }'`
    xoff=`expr $screenWidth - $twidth - 35`
    pnmcomp -yoff=$yoff -alpha alphabottom.pgm bottom.pnm sd1.pnm |\
      pnmcomp -xoff $xoff -yoff 5 -alpha alphatop.pgm top.pnm | \
      pnmtotiff > smalldisplay.tiff
else
    pnmcomp -xoff=0 -yoff=0 -alpha alphabottom.pgm bottom.pnm sd1.pnm |\
        pnmtotiff > smalldisplay.tiff
fi

tifftopnm smalldisplay.tiff | pnmtopng > smalldisplay.png

# Clean up after ourselves
rm -f text.aux text.dvi text.log textdata.* text.ps text.tex
rm -f alphabottom.pgm alpha.pnm alphatop.pgm background.pnm bottom.pnm
rm -f image.pnm imagecut.pnm sd1.pnm top.pnm
